### ISSUE TITLE
Question: How to package AppImageUpdate inside my AppImage?

### ISSUE THREAD

**Issue by OneYellowLemon** [AppImage/AppImageUpdate#201]
Hello! I am trying to bundle AppImageUpdate inside my own AppImage. I tried copying the AppImageUpdateTools AppImage into my AppDir before running `appimage-builder` but it doesn't work. The update tools hash changes as well, so something is getting corrupted. What is the proper way to do this?

**Comment by probonopd** [comment]
Hello @OneYellowLemon. If your application is a Qt application, then you might be interested in QAppImageUpdate.

in any case, if your question is about `appimage-builder` then best ask over at https://github.com/AppImageCrafters/appimage-builder/issues because I am not sure its author is reading here.
