### ISSUE TITLE
"Could NOT find CURL (missing: HTTP)" while building on Ubuntu 14

### ISSUE THREAD

**Issue by Seren541** [AppImage/AppImageUpdate#210]
While attempting to build this library on Ubuntu 14 and going through countless hurdles I finally got to this error which I have been trying to solve for days but cannot. I have found nothing online. And when I try to change build options it does not work. Is there any dependencies I need to install or options I need to set to build this library? It would be nice if you set up a "build" section in your README.

-- C++ Requests CMake Options
-- =======================================================
--   CPR_GENERATE_COVERAGE: OFF
--   CPR_CURL_NOSIGNAL: OFF
--   CPR_USE_SYSTEM_GTEST: OFF
--   CPR_FORCE_USE_SYSTEM_CURL: ON
--   CPR_ENABLE_SSL: ON
--   CPR_FORCE_OPENSSL_BACKEND: OFF
--   CPR_FORCE_WINSSL_BACKEND: OFF
--   CPR_FORCE_DARWINSSL_BACKEND: OFF
--   CPR_FORCE_MBEDTLS_BACKEND: OFF
--   CPR_ENABLE_LINTING: OFF
--   CPR_ENABLE_CPPCHECK: OFF
--   CPR_BUILD_TESTS: OFF
--   CPR_BUILD_TESTS_SSL: OFF
-- =======================================================
-- Automatically detecting SSL backend.
-- Detecting SSL backend...
-- SSL auto detect: Using OpenSSL.
-- Could NOT find CURL (missing: HTTP HTTPS) (found version "7.35.0")
-- Could NOT find CURL (missing: HTTP) (found version "7.35.0")
CMake Error at lib/zsync2/lib/cpr/CMakeLists.txt:172 (message):
  Curl not found on this system.  To use the build in version set
  CPR_FORCE_USE_SYSTEM_CURL to OFF.

**Comment by TheAssassin** [comment]
This is a bug in CMake's ` on Ubuntu I recently stumbled across, too, and it's not related to AppImageUpdate or its dependency `cpr`. Please check if `curl-config --protocols` lists `HTTP` and `HTTPS`. If that's the case, then the `pkg-config` file in `/usr/lib/x86_64-linux-gnu/pkgconfig/libcurl.pc` (when using amd64, adapt otherwise) is broken. The fix is to add `HTTP HTTPS` to `supported_protocols` there:

```
supported_protocols="DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTMP RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP"
```

**Comment by TheAssassin** [comment]
Also, Ubuntu 14.04 and 14.10 are *not* supported (there is no Ubuntu 14).

**Comment by Seren541** [comment]
What versions are supported then? I'm trying to build on an older version so that people who want to run my program on an older distro can use it.

**Comment by TheAssassin** [comment]
Ubuntu 14.04 has been end-of-life for more than three years now. Currently, the oldest still-supported Ubuntu LTS release is 18.04. This is also what we use to build AppImageUpdate on. Please note, however, that the deployment process has some complexity, since we need a C++17 compatible compiler. To build an AppImage of AppImageUpdate, use https://github.com/AppImage/AppImageUpdate/blob/main/ci/build-in-docker.sh.

This demonstrates how to set up a compatible compiler to, e.g., build libappimageupdate:

https://github.com/AppImage/AppImageUpdate/blob/af298b7aebfab4bcee7490a86f0471cc22db248b/ci/Dockerfile.x86_64#L28-L32

Note that "not supported" means "no support from the developers", not "it won't work". There are unofficial builds of libappimageupdate on CentOS 7 for instance, they just have to build almost all dependencies themselves.

**Comment by probonopd** [comment]
> Currently, the oldest still-supported Ubuntu LTS release is 18.04.

:+1:

**Comment by Seren541** [comment]
I did what you said, specifically 
`sudo sed -i 's|supported_protocols=.*|supported_protocols="DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTMP RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP"|g' /usr/lib/x86_64-linux-gnu/pkgconfig/libcurl.pc`
but it did not do anything. Instead I manually disabled the check but obviously this is not a great solution.

**Comment by TheAssassin** [comment]
Have you reset your CMake cache properly? Try with a new build directory.

**Comment by Seren541** [comment]
Undid my hack and deleted the directory and I still get the same error.
This is how /usr/lib/x86_64-linux-gnu/pkgconfig/libcurl.pc looks:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include
supported_protocols="DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP LDAPS MQTT POP3 POP3S RTMP RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP"
supported_features="SSL IPv6 libz AsynchDNS IDN NTLM NTLM_WB TLS-SRP"

Name: libcurl
URL: http://curl.haxx.se/
Description: Library to transfer files with ftp, http, etc.
Version: 7.35.0
Libs: -L${libdir} -lcurl
Libs.private: -lidn -lrtmp -lssl -lcrypto -lssl -lcrypto -Wl,-Bsymbolic-functions -Wl,-z,relro -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -llber -llber -lldap -lz
Cflags: -I${includedir} 
```

**Comment by TheAssassin** [comment]
Please provide the output of `curl-config --protocols`.

Note that this is really not AppImageUpdate's fault. If anything, you need to talk to cpr. But even they are not to blame. CMake's doing a bad job here.

Reminds me, please update your CMake version if necessary.

**Comment by Seren541** [comment]
I can certainly talk to cpr that's a good idea.
I manually updated cmake to 3.24, is that sufficient?

```
cmake -version
cmake version 3.24.0-rc2
```

```
~/gpgme-1.18.0$  curl-config --protocols
DICT
FILE
FTP
FTPS
GOPHER
HTTP
HTTPS
IMAP
IMAPS
LDAP
LDAPS
POP3
POP3S
RTMP
RTSP
SMTP
SMTPS
TELNET
TFTP
```

**Comment by TheAssassin** [comment]
3.24.0 would be latest version of CMake, you're still using a release candidate. But it's good enough.

I don't think cpr can do a lot about it, but you certainly should try. Please mention me there so I get notified and can possibly contribute.
