### ISSUE TITLE
Do not assume certain filename endings

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#24]
Do not assume certain filename suffixes. AppImages can have any or no suffix.

![screenshot from 2017-10-30 16-55-59](https://user-images.githubusercontent.com/2480569/32180822-472958ac-bd93-11e7-81f6-ee207c1ee208.png)

**Comment by TheAssassin** [comment]
The setting could be changed, but I don't want to remove it. Especially since a generic file mask is available in the dropdown as well.

The reason for this is something you as a user of live distros might not experience too often: AppImages are downloaded to my Downloads directory, but that directory contains hundreds if not thousands of files, the least of them are AppImages. Therefore, I've set it to a sane default. When navigating to my Downloads directory, it is a lot easier to find them.

Therefore, closing this issue for now, as I'm sure most people appreciate this setting.

**Comment by probonopd** [comment]
Can't we have a filter on the MIME type, for example?

**Comment by TheAssassin** [comment]
Not that I was aware of. That would also slow down the process of building the file chooser, as every file would have to be opened and read. I was happy to find that native file chooser class anyway. There's a native one which we could evaluate however, although I don't believe it'd support MIME type checks.

**Comment by probonopd** [comment]
OK, I see...

**Comment by TheAssassin** [comment]
http://www.fltk.org/doc-1.3/classFl__Native__File__Chooser.html#abf9dc3286cc673070cc62bbdbdc07203.

I guess this is due to FLTK being cross platform, they implemented the lowest common denominator, which is the filename (and therefore extension) filter.

That said, the non-native implementation only provides a filename filter as well. See http://www.fltk.org/doc-1.3/classFl__File__Chooser.html#a4f426f3b44a4727a9ed885eaeff83146.

**Comment by probonopd** [comment]
I have to say that I'm not really sold on this whole FLTK thing yet. Gtk+ 2 would be so much nicer...
