### ISSUE TITLE
Builds fail

### ISSUE THREAD

**Issue by probonopd** [AppImage/AppImageUpdate#64]
Seemingly since https://github.com/AppImage/AppImageUpdate/commit/746ef6c8ad415fd2eaadb769a0272d4fa7239540 according to the history

**Comment by antony-jr** [comment]
Do we really need **zsync2** as **zsync-curl** is much promising 👍
Big projects like Qt still uses **C** and **C++** together , Why not make **zsync-curl** a stable **C API** and then use it in **AppImageUpdate**.

**Note**: **zsync2** is causing the error , its also heavy and thus making the end result more heavier. The experimental **AppImageUpdate**(Qt Version) in my local disk is just **5 MiB**. ( Static Compiled ❤️ ) , If **FLTK** is optimized it could even beat **Qt** but there are bloats like **CPR** , **Args** and other heavy open source projects.

**Comment by probonopd** [comment]
> Do we really need zsync2 as zsync-curl is much promising 👍

zsync2 is a rewrite of zsync-curl with the stated goal of making things better.

> its also heavy and thus making the end result more heavier

How much heavier is the result when using zsync2 compared to zsync-curl?

**Comment by antony-jr** [comment]
No problem , its just my opinion. I like **C** and **C++** together , as no other language has the compability like C++ to use C legacy code. ( Its unique only to C++ )

> How much heavier is the result when using zsync2 compared to zsync-curl ?

**zsync-curl** ( Static Version , More optimized by me ) : **144 KiB** ( Before **340 KiB** )
**zsync2** ( AppImage  , Note that AppImage are also compressed ) : **2.30 MiB**

**NOTE** : We only need the client functions for the updater but zsync2 is full blown zsync implementation. Not to mention its not async , with **std::function** we could make it in async model just like Qt Signals and Slots.

**No Offense , I really like the work behind zsync2.** ( Infact , I used zsync2 as a reference for creating the AppImageUpdaterBridge , without it , It would be more difficult  ) ❤️ 👍 

**TheAssassin** did a greate work! 🥇  ( I can't get his real name 😕 )

**Comment by TheAssassin** [comment]
@antony-jr I'm really getting upset about how you try to make up arguments and get into discussing changes.

First of all, zsync2 has been developed by taking the existing zsync-curl, fixing all the architecture issues (general ones and also the ones it had because it was **never designed as a library** and hence was full of stateful global static variables etc). If you had read its page, it says

> Rewrite of https://github.com/AppImage/zsync-curl, using modern C++, providing both a library and standalone tools.

Next your so-called "comparison" is totally bogus for various reasons. zsync-curl and zsync2 share most of their code, hence the "bloat" is not coming from zsync2 being a little bit of C++ (C++ is not bloating applications!), but probably by some dependencies which are linked statically. 
However, the pure size of an application or library tells you *nothing* about the more interesting properties of software, which are performance, code quality, etc. Those are a lot more interesting and important for software development.

> NOTE : We only need the client functions for the updater but zsync2 is full blown zsync implementation. 

That sentence really shows it all. You can't really have investigated both projects. Otherwise, you'd have noticed what I said above: the core code base is shared by both projects (except for zsync2's fork having a bunch of fixes, but really, they're mostly equal). zsync-curl is *also* a "full-blown" implementation...? There is no "server" part or anything... There's just `zsyncmake`, and all the functionality for this tool is contained in both projects as well. And it's in `libzsync2` because one day we'll provide an API for this feature, allowing third-party projects like appimageupdatetool to make use of it and no longer rely on external processes (by the way, that's one of the next things I will be working on). Instead of questioning everything in general, next time ask yourself "Why are they doing it like this? Is there a greater plan that I might not know about yet?".

Then, zsync2's build isn't optimized to stripping all "non-relevant" data from the binaries. They intentionally contain debug symbols to make debugging easier, for example.

While I agree that zsync2's and AppImageUpdate's API don't make use of the entire C++11 standard (e.g., we could use futures instead of the custom API I came up with), however the API has been designed to be compatible with pre-C++11 projects as well. Sure, they still need C++11 to compile zsync2, but the API itself is compatible with previous standards. And that can be an advantage. There's lots of projects which might have heard about C++11 and newer standards, but are stuck with the old ones.

I hope it got clear that there's been a lot of architectural decisions and compromises. But going back to zsync-curl **is not and will never be** an option.

If you have questions, ask them, but please don't make wild claims this often.

__________________________________

Coming back to the _actual_ topic of this issue: @antony-jr's started a totally off-topic discussion. As this happened a few times before, I'll lock the discussion of this issue, so we can focus on fixing the actual bug @probonopd reported.
